services:
  backend:
    build: .
    environment:
      - PORT=3500
    ports:
      - 3500:3500
    volumes:
      - ./src:/app/src
  database:
    container_name: database-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: nestJS-smart-bill
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432